spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090
          jwk-set-uri: http://localhost:9090/oauth2/jwks

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/tracker
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    show-sql: false
  data:
    rest:
      default-media-type: application/json

server:
  port: 8080

logging:
  file:
    name: logger.log
    max-size: 10MB
    clean-history-on-start: false
  level:
    root: info
    com:
      tracker: info

yahoo:
  jsonExtractionStart: "root.App.main = "
  jsonExtractionEnd: "}(this));"
  baseRateClientBuys: 1.02
  baseRateClientSells: 0.98
  validityOfResponseMinutes: 15
  coreUri: "https://finance.yahoo.com/quote/"
  period1Uri: "/history?period1="
  period2Uri: "&period2="
  finalUri: "&interval=1d&filter=history&frequency=1d&includeAdjustedClose=true"
  responseHistoryStartYear: 2017
  dataReferenceDate: "1970-01-01"

