spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/tracker
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    show-sql: true
  data:
    rest:
      default-media-type: application/json

logging:
  file:
    name: logger.log
    max-size: 10MB
    clean-history-on-start: false
  level:
    root: info
    com:
      tracker: info